---
name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thanks for suggesting a new feature! Your ideas help make this integration better for everyone.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature you'd like to see.
      placeholder: "What's the feature about?"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem would this feature solve? What's your use case?
      placeholder: "Describe the problem this feature would address..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "Describe your proposed solution..."
    validations:
      required: true

  - type: dropdown
    id: integration
    attributes:
      label: Related Integration
      description: Which B2B data source or integration area does this relate to?
      options:
        - Apollo.io
        - ZoomInfo
        - Hunter.io
        - Lusha
        - Seamless.ai
        - Lead411
        - RocketReach
        - UpLead
        - BookYourData/LeadsBlue
        - New B2B Data Source
        - HaloPSA API
        - Webhooks
        - Middleware
        - Runbooks
        - Documentation
        - General/Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/blocking my work
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "What other solutions have you considered?"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or examples?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply
      options:
        - label: I have checked the [documentation](https://sjackson0109.github.io/halopsa-crm-b2b-integration/) for existing features
        - label: I have searched existing issues for similar requests
        - label: This feature would benefit other users
        - label: I am willing to help implement this feature