---
name: Security Vulnerability
description: Report a security vulnerability privately
title: "[SECURITY] "
labels: ["security", "vulnerability"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Security Vulnerability Report

        **This form is for reporting security vulnerabilities only.**

        If you believe you've found a security vulnerability in this project, please report it responsibly. We take security seriously and will investigate all legitimate reports.

        **Please do not disclose vulnerability details publicly until we've had a chance to investigate and fix the issue.**

  - type: textarea
    id: summary
    attributes:
      label: Vulnerability Summary
      description: Brief description of the potential security issue (avoid specific exploit details if reporting publicly).
      placeholder: "High-level description of the security concern..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe do you believe this vulnerability is?
      options:
        - Critical - Immediate threat to data/security
        - High - Significant security risk
        - Medium - Moderate security concern
        - Low - Minor security issue
        - Info - Potential security improvement
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Data Exposure/Leakage
        - Injection (SQL, NoSQL, Command, etc.)
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Server-Side Request Forgery (SSRF)
        - Remote Code Execution (RCE)
        - Privilege Escalation
        - API Security
        - Configuration Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker potentially do with this vulnerability?
      placeholder: "Describe the potential security impact..."

  - type: textarea
    id: affected
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: "Which integrations, APIs, or components are vulnerable?"

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced? (You may provide this privately if preferred)
      placeholder: "Detailed reproduction steps (consider providing privately)..."

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to fix this?
      placeholder: "Any recommendations for addressing this vulnerability?"

  - type: textarea
    id: contact
    attributes:
      label: Contact Information
      description: How can we follow up with you about this report?
      placeholder: "Email, preferred contact method, or leave blank for anonymous report"

  - type: checkboxes
    id: disclosure
    attributes:
      label: Disclosure Agreement
      description: Please confirm the following
      options:
        - label: I understand that this is a responsible disclosure and will not publicly disclose details until the issue is resolved
        - label: I have not exploited this vulnerability beyond verification
        - label: I am reporting this in good faith